import type { ClinicApplication, SystemLog } from '../types';

export const APPLICATION_FACILITY_TYPES = [
  'CHPS Compound',
  'Health Centre',
  'Clinic',
  'District Hospital',
  'Regional Hospital',
  'Teaching Hospital',
  'Other',
] as const;

export const FACILITY_TYPES = [
  'Hospital',
  'Clinic',
  'Polyclinic',
  'Health Centre',
  'Maternity Home',
  'CHPS Compound',
] as const;

export const GHANA_REGIONS = [
  'Greater Accra',
  'Ashanti',
  'Western',
  'Central',
  'Eastern',
  'Northern',
  'Upper East',
  'Upper West',
  'Volta',
  'Bono',
  'Bono East',
  'Ahafo',
  'Western North',
  'Oti',
  'North East',
  'Savannah',
] as const;

export const initialApplications: ClinicApplication[] = [
  {
    id: 'app-001',
    facilityName: 'Sunrise Maternity Clinic',
    hefraLicenceNumber: 'HFR-ACC-2024-1182',
    facilityType: 'Clinic',
    region: 'Greater Accra',
    district: 'La Dade Kotopon',
    officialEmail: 'admin@sunrisematernity.gh',
    phoneNumber: '+233 24 555 0192',
    contactPersonName: 'Dr. Ama Mensah',
    contactPersonRole: 'Medical Director',
    hefraDocumentName: 'sunrise-hefra-licence.pdf',
    status: 'pending',
    submittedAt: '2026-03-10T09:15:00.000Z',
  },
  {
    id: 'app-002',
    facilityName: 'Hope Valley Hospital',
    hefraLicenceNumber: 'HFR-ASH-2023-0441',
    facilityType: 'Hospital',
    region: 'Ashanti',
    district: 'Kumasi Metropolitan',
    officialEmail: 'partnerships@hopevalley.gh',
    phoneNumber: '+233 20 441 8820',
    contactPersonName: 'Mr. Kwesi Owusu',
    contactPersonRole: 'Hospital Administrator',
    hefraDocumentName: 'hopevalley-hefra.pdf',
    status: 'pending',
    submittedAt: '2026-03-12T14:30:00.000Z',
  },
  {
    id: 'app-003',
    facilityName: 'CareNest Polyclinic',
    hefraLicenceNumber: 'HFR-CEN-2022-0098',
    facilityType: 'Polyclinic',
    region: 'Central',
    district: 'Cape Coast Metropolitan',
    officialEmail: 'info@carenest.gh',
    phoneNumber: '+233 55 902 1144',
    contactPersonName: 'Mrs. Efua Boateng',
    contactPersonRole: 'Operations Manager',
    hefraDocumentName: 'carenest-hefra-licence.pdf',
    status: 'approved',
    submittedAt: '2026-02-20T11:00:00.000Z',
    reviewedAt: '2026-02-22T10:20:00.000Z',
    activationToken: 'MAT-CARENEST-2026',
    accountStatus: 'Pending Activation',
    activationStatus: 'Link Sent',
  },
  {
    id: 'app-004',
    facilityName: 'GreenLife Health Centre',
    hefraLicenceNumber: 'HFR-VOL-2021-0330',
    facilityType: 'Health Centre',
    region: 'Volta',
    district: 'Ho Municipal',
    officialEmail: 'contact@greenlife.gh',
    phoneNumber: '+233 27 330 7781',
    contactPersonName: 'Dr. Yaw Adjei',
    contactPersonRole: 'Facility Head',
    hefraDocumentName: 'greenlife-hefra.pdf',
    status: 'rejected',
    submittedAt: '2026-02-05T08:45:00.000Z',
    reviewedAt: '2026-02-07T16:10:00.000Z',
    rejectionReason: 'Incomplete documentation. HeFRA licence document could not be verified.',
  },
];

export const initialLogs: SystemLog[] = [
  {
    id: 'log-001',
    action: 'Application Submitted',
    details: 'Sunrise Maternity Clinic submitted a new registration application.',
    timestamp: '2026-03-10T09:15:00.000Z',
  },
  {
    id: 'log-002',
    action: 'Application Submitted',
    details: 'Hope Valley Hospital submitted a new registration application.',
    timestamp: '2026-03-12T14:30:00.000Z',
  },
  {
    id: 'log-003',
    action: 'Application Approved',
    details: 'CareNest Polyclinic was approved. Activation link sent to info@carenest.gh.',
    timestamp: '2026-02-22T10:20:00.000Z',
  },
  {
    id: 'log-004',
    action: 'Application Rejected',
    details: 'GreenLife Health Centre application was rejected due to incomplete documentation.',
    timestamp: '2026-02-07T16:10:00.000Z',
  },
];
