import type { ClinicApplication, SystemLog } from '../types';

export const APPLICATION_FACILITY_TYPES = [
  'CHPS Compound',
  'Health Centre',
  'Maternity Home',
  'Polyclinic',
  'Private Clinic',
  'District Hospital',
  'Regional Hospital',
  'Teaching Hospital',
  'Specialist Hospital',
  'Mission/Faith-Based Hospital',
  'Other',
] as const;

export const REPRESENTATIVE_POSITIONS = [
  'Medical Superintendent',
  'Medical Director',
  'Midwife in Charge',
  'Nurse in Charge',
  'Facility Administrator',
  'Facility Manager',
  'Other',
] as const;

export const FACILITY_TYPES = [
  'Hospital',
  'Clinic',
  'Polyclinic',
  'Health Centre',
  'Maternity Home',
  'CHPS Compound',
] as const;

type PendingClinicSeed = Omit<
  ClinicApplication,
  'id' | 'status' | 'submittedAt' | 'reviewedAt' | 'rejectionReason' | 'activationToken' | 'accountStatus' | 'activationStatus'
>;

const pendingClinicSeeds: PendingClinicSeed[] = [
  {
    facilityName: 'Sunrise Maternity Clinic',
    hefraLicenceNumber: 'HFR-ACC-2024-1182',
    facilityType: 'Clinic',
    region: 'Greater Accra',
    district: 'La Dade Kotopon',
    officialEmail: 'admin@sunrisematernity.gh',
    phoneNumber: '+233 24 555 0192',
    contactPersonName: 'Dr. Ama Mensah',
    contactPersonRole: 'Medical Director',
    hefraDocumentName: 'sunrise-hefra-licence.pdf',
  },
  {
    facilityName: 'Hope Valley Hospital',
    hefraLicenceNumber: 'HFR-ASH-2023-0441',
    facilityType: 'Hospital',
    region: 'Ashanti',
    district: 'Kumasi Metropolitan',
    officialEmail: 'partnerships@hopevalley.gh',
    phoneNumber: '+233 20 441 8820',
    contactPersonName: 'Mr. Kwesi Owusu',
    contactPersonRole: 'Hospital Administrator',
    hefraDocumentName: 'hopevalley-hefra.pdf',
  },
  {
    facilityName: 'MotherCare Antenatal Centre',
    hefraLicenceNumber: 'HFR-ACC-2025-2201',
    facilityType: 'Clinic',
    region: 'Greater Accra',
    district: 'Tema West',
    officialEmail: 'info@mothercare.gh',
    phoneNumber: '+233 55 210 3344',
    contactPersonName: 'Dr. Abena Kwarteng',
    contactPersonRole: 'Clinical Lead',
    hefraDocumentName: 'mothercare-hefra.pdf',
  },
  {
    facilityName: 'New Life Maternity Home',
    hefraLicenceNumber: 'HFR-EAS-2024-0876',
    facilityType: 'Maternity Home',
    region: 'Eastern',
    district: 'New Juaben South',
    officialEmail: 'contact@newlifematernity.gh',
    phoneNumber: '+233 24 778 9012',
    contactPersonName: 'Mrs. Grace Ofori',
    contactPersonRole: 'Matron',
    hefraDocumentName: 'newlife-hefra-licence.pdf',
  },
  {
    facilityName: "Ridge Women's Health Clinic",
    hefraLicenceNumber: 'HFR-ACC-2023-1560',
    facilityType: 'Clinic',
    region: 'Greater Accra',
    district: 'Accra Metropolitan',
    officialEmail: 'admin@ridgewomens.gh',
    phoneNumber: '+233 30 221 4455',
    contactPersonName: 'Dr. Esi Lamptey',
    contactPersonRole: 'Medical Director',
    hefraDocumentName: 'ridge-womens-hefra.pdf',
  },
  {
    facilityName: 'Komfo Anokye Annex Clinic',
    hefraLicenceNumber: 'HFR-ASH-2024-3312',
    facilityType: 'Polyclinic',
    region: 'Ashanti',
    district: 'Oforikrom Municipal',
    officialEmail: 'anc@kaannex.gh',
    phoneNumber: '+233 32 202 1188',
    contactPersonName: 'Dr. Yaw Boateng',
    contactPersonRole: 'Facility Head',
    hefraDocumentName: 'ka-annex-hefra.pdf',
  },
  {
    facilityName: 'Cape Coast Family Hospital',
    hefraLicenceNumber: 'HFR-CEN-2025-0044',
    facilityType: 'Hospital',
    region: 'Central',
    district: 'Cape Coast Metropolitan',
    officialEmail: 'registry@capefamily.gh',
    phoneNumber: '+233 33 213 7700',
    contactPersonName: 'Mr. Kojo Andoh',
    contactPersonRole: 'Hospital Administrator',
    hefraDocumentName: 'cape-family-hefra.pdf',
  },
  {
    facilityName: 'Tamale Maternal Wellness Centre',
    hefraLicenceNumber: 'HFR-NOR-2024-0911',
    facilityType: 'Health Centre',
    region: 'Northern',
    district: 'Tamale Metropolitan',
    officialEmail: 'hello@tamalematernal.gh',
    phoneNumber: '+233 37 209 5566',
    contactPersonName: 'Dr. Fuseini Alhassan',
    contactPersonRole: 'Medical Superintendent',
    hefraDocumentName: 'tamale-maternal-hefra.pdf',
  },
  {
    facilityName: 'Blessed Beginnings Clinic',
    hefraLicenceNumber: 'HFR-VOL-2025-0178',
    facilityType: 'Clinic',
    region: 'Volta',
    district: 'Ho Municipal',
    officialEmail: 'team@blessedbeginnings.gh',
    phoneNumber: '+233 36 202 4411',
    contactPersonName: 'Mrs. Selasi Agbeko',
    contactPersonRole: 'Operations Manager',
    hefraDocumentName: 'blessed-beginnings-hefra.pdf',
  },
  {
    facilityName: 'Western Care Polyclinic',
    hefraLicenceNumber: 'HFR-WES-2023-2209',
    facilityType: 'Polyclinic',
    region: 'Western',
    district: 'Sekondi-Takoradi Metropolitan',
    officialEmail: 'info@westerncare.gh',
    phoneNumber: '+233 31 229 8800',
    contactPersonName: 'Dr. Akua Mensah',
    contactPersonRole: 'Medical Director',
    hefraDocumentName: 'western-care-hefra.pdf',
  },
  {
    facilityName: 'Bolgatanga Community Health Centre',
    hefraLicenceNumber: 'HFR-UE-2024-0633',
    facilityType: 'Health Centre',
    region: 'Upper East',
    district: 'Bolgatanga Municipal',
    officialEmail: 'admin@bolgacommunity.gh',
    phoneNumber: '+233 38 202 1199',
    contactPersonName: 'Mr. Richard Akurugu',
    contactPersonRole: 'Facility Manager',
    hefraDocumentName: 'bolga-community-hefra.pdf',
  },
  {
    facilityName: 'Wa Hope Maternity Clinic',
    hefraLicenceNumber: 'HFR-UW-2025-0087',
    facilityType: 'Clinic',
    region: 'Upper West',
    district: 'Wa Municipal',
    officialEmail: 'care@wahope.gh',
    phoneNumber: '+233 39 209 7744',
    contactPersonName: 'Dr. Patience Dery',
    contactPersonRole: 'Clinical Lead',
    hefraDocumentName: 'wa-hope-hefra.pdf',
  },
  {
    facilityName: 'Sunyani Reproductive Health Centre',
    hefraLicenceNumber: 'HFR-BON-2024-1440',
    facilityType: 'Health Centre',
    region: 'Bono',
    district: 'Sunyani Municipal',
    officialEmail: 'anc@sunyanirhc.gh',
    phoneNumber: '+233 35 202 6600',
    contactPersonName: 'Dr. Emmanuel Boahen',
    contactPersonRole: 'Medical Director',
    hefraDocumentName: 'sunyani-rhc-hefra.pdf',
  },
  {
    facilityName: 'Koforidua Grace Hospital',
    hefraLicenceNumber: 'HFR-EAS-2023-1992',
    facilityType: 'Hospital',
    region: 'Eastern',
    district: 'New Juaben North',
    officialEmail: 'partners@koforiduagrace.gh',
    phoneNumber: '+233 34 202 3388',
    contactPersonName: 'Mrs. Akosua Frimpong',
    contactPersonRole: 'Hospital Administrator',
    hefraDocumentName: 'koforidua-grace-hefra.pdf',
  },
  {
    facilityName: 'Takoradi Bay Maternity Home',
    hefraLicenceNumber: 'HFR-WES-2025-0315',
    facilityType: 'Maternity Home',
    region: 'Western',
    district: 'Effia-Kwesimintsim Municipal',
    officialEmail: 'info@takoradibay.gh',
    phoneNumber: '+233 24 901 2233',
    contactPersonName: 'Mrs. Victoria Eshun',
    contactPersonRole: 'Matron',
    hefraDocumentName: 'takoradi-bay-hefra.pdf',
  },
  {
    facilityName: 'Techiman Unity Clinic',
    hefraLicenceNumber: 'HFR-BE-2024-0771',
    facilityType: 'Clinic',
    region: 'Bono East',
    district: 'Techiman Municipal',
    officialEmail: 'admin@techimanunity.gh',
    phoneNumber: '+233 20 552 8890',
    contactPersonName: 'Dr. Isaac Osei',
    contactPersonRole: 'Medical Director',
    hefraDocumentName: 'techiman-unity-hefra.pdf',
  },
  {
    facilityName: 'Goaso Maternal Care CHPS',
    hefraLicenceNumber: 'HFR-AHA-2025-0026',
    facilityType: 'CHPS Compound',
    region: 'Ahafo',
    district: 'Asunafo North',
    officialEmail: 'chps@goasomaternal.gh',
    phoneNumber: '+233 55 440 1122',
    contactPersonName: 'Mr. Francis Adu',
    contactPersonRole: 'Community Health Officer',
    hefraDocumentName: 'goaso-chps-hefra.pdf',
  },
  {
    facilityName: "Sefwi Wiawso Women's Clinic",
    hefraLicenceNumber: 'HFR-WN-2024-0559',
    facilityType: 'Clinic',
    region: 'Western North',
    district: 'Sefwi Wiawso Municipal',
    officialEmail: 'care@sefwiwomens.gh',
    phoneNumber: '+233 24 330 7788',
    contactPersonName: 'Dr. Linda Amoah',
    contactPersonRole: 'Facility Head',
    hefraDocumentName: 'sefwi-womens-hefra.pdf',
  },
  {
    facilityName: 'Dambai Antenatal Health Centre',
    hefraLicenceNumber: 'HFR-OTI-2025-0114',
    facilityType: 'Health Centre',
    region: 'Oti',
    district: 'Krachi East',
    officialEmail: 'hello@dambaianc.gh',
    phoneNumber: '+233 50 881 4400',
    contactPersonName: 'Mrs. Comfort Adjei',
    contactPersonRole: 'Nurse Manager',
    hefraDocumentName: 'dambai-anc-hefra.pdf',
  },
  {
    facilityName: 'Nalerigu Family Care Hospital',
    hefraLicenceNumber: 'HFR-NE-2024-0288',
    facilityType: 'Hospital',
    region: 'North East',
    district: 'East Mamprusi Municipal',
    officialEmail: 'registry@nalerigufamily.gh',
    phoneNumber: '+233 37 704 2299',
    contactPersonName: 'Dr. Mahama Yakubu',
    contactPersonRole: 'Medical Superintendent',
    hefraDocumentName: 'nalerigu-family-hefra.pdf',
  },
];

function daysAgoIso(days: number, hour = 10): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

const pendingApplications: ClinicApplication[] = pendingClinicSeeds.map((seed, index) => ({
  ...seed,
  id: `app-${String(index + 1).padStart(3, '0')}`,
  status: 'pending',
  submittedAt: daysAgoIso(20 - index, 9 + (index % 6)),
}));

export const initialApplications: ClinicApplication[] = [
  ...pendingApplications,
  {
    id: 'app-approved-001',
    facilityName: 'CareNest Polyclinic',
    hefraLicenceNumber: 'HFR-CEN-2022-0098',
    facilityType: 'Polyclinic',
    region: 'Central',
    district: 'Cape Coast Metropolitan',
    officialEmail: 'info@carenest.gh',
    phoneNumber: '+233 55 902 1144',
    contactPersonName: 'Mrs. Efua Boateng',
    contactPersonRole: 'Operations Manager',
    hefraDocumentName: 'carenest-hefra-licence.pdf',
    status: 'approved',
    submittedAt: '2026-02-20T11:00:00.000Z',
    reviewedAt: '2026-02-22T10:20:00.000Z',
    activationToken: 'MAT-CARENEST-2026',
    accountStatus: 'Pending Activation',
    activationStatus: 'Link Sent',
  },
  {
    id: 'app-rejected-001',
    facilityName: 'GreenLife Health Centre',
    hefraLicenceNumber: 'HFR-VOL-2021-0330',
    facilityType: 'Health Centre',
    region: 'Volta',
    district: 'Ho Municipal',
    officialEmail: 'contact@greenlife.gh',
    phoneNumber: '+233 27 330 7781',
    contactPersonName: 'Dr. Yaw Adjei',
    contactPersonRole: 'Facility Head',
    hefraDocumentName: 'greenlife-hefra.pdf',
    status: 'rejected',
    submittedAt: '2026-02-05T08:45:00.000Z',
    reviewedAt: '2026-02-07T16:10:00.000Z',
    rejectionReason: 'Incomplete documentation. HeFRA licence document could not be verified.',
  },
];

export const initialLogs: SystemLog[] = [
  ...pendingApplications.slice(0, 5).map((application, index) => ({
    id: `log-pending-${String(index + 1).padStart(3, '0')}`,
    action: 'Application Submitted',
    details: `${application.facilityName} submitted a new registration application.`,
    timestamp: application.submittedAt,
  })),
  {
    id: 'log-approved-001',
    action: 'Application Approved',
    details: 'CareNest Polyclinic was approved. Activation link sent to info@carenest.gh.',
    timestamp: '2026-02-22T10:20:00.000Z',
  },
  {
    id: 'log-rejected-001',
    action: 'Application Rejected',
    details: 'GreenLife Health Centre application was rejected due to incomplete documentation.',
    timestamp: '2026-02-07T16:10:00.000Z',
  },
];
